-- MySQL Script generated by MySQL Workbench
-- 12/20/16 12:24:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `qty` INT NULL,
  `price` INT NULL,
  `nrSold` INT NULL,
  `image` VARCHAR(180) NULL,
  `category` VARCHAR(45) NULL,
  `description` VARCHAR(180) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(18) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `lastname` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `credit` INT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`shoppingCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shoppingCart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NULL,
  `bookid` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shoppingCart_user_idx` (`userid` ASC),
  INDEX `fk_shoppingCart_book1_idx` (`bookid` ASC),
  CONSTRAINT `fk_shoppingCart_user`
    FOREIGN KEY (`userid`)
    REFERENCES `mydb`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shoppingCart_book1`
    FOREIGN KEY (`bookid`)
    REFERENCES `mydb`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bookOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bookOrder` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bookid` INT NOT NULL,
  `userid` INT NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`, `bookid`, `userid`),
  INDEX `fk_Order_book1_idx` (`bookid` ASC),
  INDEX `fk_Order_user1_idx` (`userid` ASC),
  CONSTRAINT `fk_Order_book1`
    FOREIGN KEY (`bookid`)
    REFERENCES `mydb`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `mydb`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NULL,
  `info` VARCHAR(150) NULL,
  `answer` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ticket_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `mydb`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
